### ISSUE TITLE
TTPS in ordered position don't execute in order.

### ISSUE THREAD

**Issue by gerbsec** [preludeorg/operator-support#529] opened 2022-05-25 20:16 UTC
Executing my ttps, execute in whatever order they want:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/67713732/170352289-83ca5b9f-60c5-4abe-9142-e79d2b290a99.png">

**Comment by privateducky** [comment] 2022-05-27 14:06
Closing, as duplicate of https://github.com/preludeorg/operator-support/issues/527

**Closed by privateducky** 2022-05-27 14:06 UTC
