### ISSUE TITLE
Unhandled Payload Exception for TTP's with External Dependency

### ISSUE THREAD

**Issue by phage-nz** [preludeorg/operator-support#121] opened 2021-03-08 22:28 UTC
Hi,

I've been trying to run some TTP's that have an external dependency that sits under %APPDATA%\Operator\workspace\payloads\professional\ and are referenced in the TTP configurations as #{operator.payload}, but they all fail with this error when run:
![image](https://user-images.githubusercontent.com/18238564/110389114-eb094580-80c8-11eb-8763-10448632b8d0.png)
![image](https://user-images.githubusercontent.com/18238564/110389568-9619ff00-80c9-11eb-80d4-f3c0ceefa41b.png)
Am I missing a pre-requisite configuration here? Do I need to define this path somewhere? Works fine on the home range but not the red range. Are they not copied over to the targets?

Using version 0.9.15.

Thanks!

**Comment by khyberspache** [comment] 2021-03-08 22:36
So this error indicates that the agent isn't able to reach back and download the payload from the  C2 server.  This could be caused by a few different issues.  What does your network configuration look like? If it's working on the home range that means you already have the payloads accessible and it's an issue with the agent not getting a response from your Operator instance.

**Comment by khyberspache** [comment] 2021-03-08 22:38
If you run pneuma with the `-debug` flag you should see the attempt to download the payload. What does the console output look like for pneuma when you run it with that flag?

**Comment by phage-nz** [comment] 2021-03-08 22:55
If running pneuma with the debug flag and a test adversary with the 4 TTP's (the 2 in the original post plus 2 others that are pure PowerShell commands) I have 2 log entries that state: Running instruction. I assume this is for the 2 PowerShell commands that succeed. The failure of the other 2 is almost instant.

Network in this case is 2 hosts on the same subnet in our lab.

**Comment by khyberspache** [comment] 2021-03-08 23:38
From your agent host, can you try cURLing/invoke-restmethod against your operator host?

`curl http://<server>:3391/payloads/mitre/apt29/stepThirteen.ps1`

`Invoke-WebRequest -uri http://<server>:3391/payloads/mitre/apt29/stepThirteen.ps1

**Comment by phage-nz** [comment] 2021-03-08 23:45
I get a 404 response for that. Same in a browser.

**Comment by khyberspache** [comment] 2021-03-09 00:04
On your settings page, is your HTTP exposed port the default 3391?

**Comment by phage-nz** [comment] 2021-03-09 01:40
Yep:
![image](https://user-images.githubusercontent.com/18238564/110405139-f9655a80-80e4-11eb-83e5-58e196bf6948.png)
![image](https://user-images.githubusercontent.com/18238564/110405300-3cbfc900-80e5-11eb-9abf-300119eba6b4.png)

**Comment by khyberspache** [comment] 2021-03-09 01:57
Can you try exposing all interfaces with `0.0.0.0` and see if you are able to grab the payload using curl/irm/web browser?

**Comment by phage-nz** [comment] 2021-03-09 02:03
Unfortunately still get the same issue. Connection is fine, but 404 response.
![image](https://user-images.githubusercontent.com/18238564/110407205-59a9cb80-80e8-11eb-8231-4225d486e23b.png)
Have tried with `http://IP:3391/payloads/professional/mitre/apt29/stepThirteen.ps1` too.

**Comment by khyberspache** [comment] 2021-03-09 02:13
From you operator host, can you hit `http://localhost:3391/payloads/mitre/apt29/stepThirteen.ps1`?

**Comment by phage-nz** [comment] 2021-03-09 02:21
No, also get a 404 from that. Same with `http://localhost:3391/payloads/AdFind/AdFind.exe`.

**Comment by khyberspache** [comment] 2021-03-09 03:05
Is it 404 `'Not found.'` specifically?

**Comment by phage-nz** [comment] 2021-03-09 03:08
Yes. PowerShell response:
![image](https://user-images.githubusercontent.com/18238564/110412775-9a5a1280-80f1-11eb-855e-aecfa0dced88.png)

Web browser:
![image](https://user-images.githubusercontent.com/18238564/110412821-b067d300-80f1-11eb-8103-62ba2320342f.png)

**Comment by khyberspache** [comment] 2021-03-09 03:16
You said that these TTPs would run from on the home range though? 

It would make more sense if the payloads were just not in the folder...  You might try downloading the payloads again and seeing if that fixes the issue?  You can do that from the Editor pane using the down arrow on the right hadn't side:
<img width="1512" alt="CleanShot 2021-03-08 at 22 16 03@2x" src="https://user-images.githubusercontent.com/43142871/110413461-e195c400-805b-11eb-800e-17eb72bbd08e.png">

I'm marking this as a bug, because something is not functioning properly.  I'll re-engage on this tomorrow morning.

**Comment by phage-nz** [comment] 2021-03-09 08:21
Thanks!

Yes, they did run locally. I have run Operator up on a fresh Server 2016 host (Defender AV+firewall disabled to ensure no conflict) to rule out potential conflicts on the lab workstation and still get a 404 response. Testing locally here, it looks to be pulling the files from the staging directory (where the files exist) - unsure if expected:
![image](https://user-images.githubusercontent.com/18238564/110433663-a2c44480-8115-11eb-8a59-097b9aa8b595.png)
I've installed it on a new Ubuntu 20.04 box and it seems to be behaving, so that'll work fine for now. No 404 on `http://IP:3391/payloads/AdFind/AdFind.exe`.

Happy to help continue trying to diagnose the Windows issue in case others run into it too.

**Comment by khyberspache** [comment] 2021-03-09 15:51
@lzimm Can you jump in here? I was thinking this might be a path resolution issue, but it's strange that the payloads are available to the node agent on the home range.

**Closed** 2021-03-13 11:54 UTC
Labels: 0.9.17, bug
