### ISSUE TITLE
Connecting to AWS redirector throws error

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#462] opened 2022-04-07 23:57 UTC
I provisioned and then tried to connect to my redirector and it throw the following error. Functionality seems to be fine though. 
<img width="336" alt="Screen Shot 2022-04-07 at 7 57 15 PM" src="https://user-images.githubusercontent.com/84744117/162337769-77966edf-f1e8-4989-ab7d-665327c3f78e.png">

**Comment by privateducky** [comment] 2022-04-10 11:18
cannot reproduce this. 

@stephanwampouille closing as it seems inconsequential - but please let me know if you can still see this.

**Closed by privateducky** 2022-04-10 11:18 UTC
Labels: bug
