### ISSUE TITLE
JS UI bug when clicking "hint" during Introduction Training

### ISSUE THREAD

**Issue by kwadner** [preludeorg/operator-support#329] opened 2021-08-30 22:23 UTC
During the _emulation_ phase of the Introduction Training I clicked "hint" button at the top prior to doing anything because it was not clear what the necessary steps were. This resulted in the loading square of dots to stay visible and no hint to be displayed. Looking at the Developer Tools, there is Uncaught TypeError that appears related.

![image](https://user-images.githubusercontent.com/2546881/131413308-1b9ee43e-18bc-48a7-b522-abe41b469a6c.png)

Navigating away, and then back, followed by pressing "Verify" correctly shows the hint. I've observed this on _Reverse Shell_ and _Adversary goals_.

**Comment by privateducky** [comment] 2021-08-30 22:31
Duplicate of: https://github.com/preludeorg/operator-support/issues/319

FIxed in the master branch and will be available in the next build.

**Closed** 2021-09-24 10:43 UTC
Labels: bug, duplicate, 1.2.0
