### ISSUE TITLE
No notification received for Pneuma download

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#338] opened 2021-09-02 18:51 UTC
Most of the time I go to the Agent Library and click on Pneuma Windows from my Windows server 2019 machine I never get any notification that something has downloaded and there is nothing in the text to indicate we should go look in c:\users\public to find it, so if we don't know to expect no output and to go look in C:\users\public then we are left confused.

**Comment by privateducky** [comment] 2021-09-02 19:02
Do you get any notifications from Operator? Depending on your OS/settings, you may have notifications disabled for the app, which will silence them.

**Comment by clr2of8** [comment] 2021-09-02 19:06
Sometimes ... This is a default win 10 install with default notification settings. It's the same as the test VM I provided to you so if you have a minute, can you try it out there?

**Comment by VVX7** [comment] 2021-09-03 13:48
I'm able to reproduce this on my Win10 machine with default notification settings.

**Comment by privateducky** [comment] 2021-09-03 14:07
re-labeling as a bug. we'll investigate before 1.2.

**Comment by privateducky** [comment] 2021-09-07 12:50
@khyberspache do you have any thoughts? this seems to be in your area of expertise.

**Comment by sanoopsktm-git** [comment] 2021-09-10 22:16
I have seen the agent is downloaded in to C:\Users\public folder < windows platform >

**Comment by privateducky** [comment] 2021-09-11 00:13
Confirmed. We will be testing our built-in notifications (for things like agent downloads) on this platform. Look for an update next week, before our 1.2 release.

**Comment by privateducky** [comment] 2021-11-15 17:58
This will be resolved in version 1.3.

**Closed** 2021-11-19 19:20 UTC
Labels: bug, 1.3.0
