### ISSUE TITLE
Windows Server 2019 VM UI Bugs

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#339] opened 2021-09-03 15:54 UTC
Through my QA testing on the VM with Operator there are a couple faulty UI buttons. With that being said there are similar issues on Github's page when trying to download code. With those similarities it may be a fault of the VM environment.

- 'Update Available' on the main dashboard
- With the error Carrie found (see below)about breaking the UI if you click out of Operator and click back in it fixes
- 'download starter kit link' on Toolbox
- download agents do not send a notification

Carrie's bug find:
"OK, I found the following steps to consistently break the UI:
1) Editor -> Click here to create a TTP
2) Click the up arrow for "Import TTP" on the right menu bar, enter "c" as the directory path and click the import button
3) dismiss directory not found dialog, and X out of the "Import TTP" dialog
4) Try to select a tactic from the select box"

**Comment by privateducky** [comment] 2021-09-03 15:55
@stephanwampouille what makes you think this is a VM issue and not Operator specific?

**Comment by stephanwampouille** [comment] 2021-09-03 16:30
@privateducky Seeing that there are similar button faults within the GitHub page and Operator button functionality, there may be a comparison in error. The UI issue may be Operator side as the application seems to lose focus and then redirects back once clicked out and in. I know understand that the 'download starter kit' button doesn't work since git is not installed. This may be an issue with the rest of the bugs as well and a fault of the environment setup.

**Comment by privateducky** [comment] 2021-09-06 15:07
@clr2of8 it seems like the VM environment itself may be the root of a variety of GUI bugs we noticed in the WIndows Server 2019 environment. Certain elements, like inputs or buttons, that didn't work in Operator also didn't work in the browser app on the box either. I'm not sure what would be the root cause of this but definitely worth looking into. 

On our end, we'll try to spin up a similar environment for this OS but in a different environment, to see if we have the same/different experience.

**Comment by privateducky** [comment] 2021-09-17 13:58
closing, as we're unable to reproduce these issues in an environment where the same GUI problems don't exist with the browser (in general).

**Closed by privateducky** 2021-09-17 13:58 UTC
Labels: documentation
